### ISSUE TITLE
Reconsider name

### ISSUE THREAD

**Issue by Artanicus** [PremoWeb/chadburn#1]
While Chronos is an amazing name, it's already in use by a well known cron repoacement: https://github.com/mesos/chronos

TikTok eould also work but also taken 😅

**Comment by user592965** [comment]
Hello, I suggest Quartz because every good watch has a quartz
Or "Chadburn" the engine order telegraph on ships, to stay in the theme of containers ;)

**Comment by maietta** [comment]
Ouch! How did I not realize I should be checking for a conflict! Nice name suggestions. Another ouch -- all the work that went into changing the code from Ofelia to Chronos, setting up services, etc. Yikes! I fully agree with you! Clearly, I should not use a name that conflicts with another project that is an alternative to cron.

Quartz sounds pretty nice, but the name Chadburn-- now that is unique and unlikely to present a conflict in the future. I really like the idea of keeping with the theme of Ships, as our focus is taking care of our containers as they move around!

I'll accept Chadburn as it's a device used to communicate orders to those who perform the critical work, like operating an engine, etc. Fits very nicely with the project's purpose.

Excellent first issue raised. Thank you.

**Comment by maietta** [comment]
I've completed the work to rename the project.

Thanks again!
