### ISSUE TITLE
Feature request: Send logs to a syslog server

### ISSUE THREAD

**Issue by theonelucas** [PremoWeb/chadburn#10]
Hi, is there any intent to implement logging using a syslog server, such as rsyslog?

I have an infrastructure with quite a few services all logging to rsyslog already, except for Chadburn. If that's something desirable, I could try my hand at implementing it, let me know what you guys think.

**Comment by maietta** [comment]
Yes. External logging is extremely desirable and help from others such as yourself would be greatly appreciated!

An issue was previously raised about logging to Prometheus but I ran into some issues getting a working Prometheus server. (Perhaps I didn't know what I was doing)

That issue raised was converted to a Discussion page which can be found here: https://github.com/PremoWeb/chadburn/discussions/4

**Comment by theonelucas** [comment]
Cool, will continue the discussion there then
