### ISSUE TITLE
Mail notifications fail with unknown certificate

### ISSUE THREAD

**Issue by rgomez-eng** [PremoWeb/chadburn#22]
We using custom CA on our SMTP server and we get following error.
`
mail.go:57 ▶ ERROR Mail error: "x509: certificate signed by unknown authority"`

Any idea how to fix it?

**Comment by maietta** [comment]
Don't think its an issue with Chadburn (fork of Ofelia) but I'll be glad to help trace the issue.

Do this:

Take the domain part of the email address, and plug it into a website like https://mxtoolbox.com/MXLookup.aspx.

You'll get back a list of MX hostname entries, usually one for small sites. Big email providers have 2-3.

Now take that MX hostname and verify it's SSL with a site like https://www.sslshopper.com/ssl-checker.html.

For example:

My email, xxxx@premoweb.com,the domain being premoweb.com has an MX entry of mail.premoweb.com.
The SSL lookup shows the following:
![image](https://user-images.githubusercontent.com/11745020/174321632-d813b913-62ef-4641-97f5-3ca042fe0b0c.png)

Awaiting your response.

**Comment by rgomez-eng** [comment]
As I said we use own CA and not a publicly trusted one so I guess that's issue. Anyway to disable this verification or to add a trusted CA ?

**Comment by maietta** [comment]
Sorry I glossed over the part where you are using your own CA. I was quite busy on other things, so I guess I didn't pay attention.

The Chadburn library makes use of a 3rd party library found here: https://pkg.go.dev/gopkg.in/gomail.v2

Reading up on the 3rd party library, it does appear that there is an option to skip SSL verification from general public trust sources.
https://pkg.go.dev/gopkg.in/gomail.v2#readme-x509-certificate-signed-by-unknown-authority

This appears to be an easy enough fix on my end. I'll try and get a patch available today for you, pending cooperation from the universe.

I'll follow up a bit later today.

**Comment by maietta** [comment]
I have patched in 2 small changes to add this config option but am not setup to test this. I have tagged this release as v1.0.2.

New release:
https://github.com/PremoWeb/chadburn/releases/tag/v1.0.2

Please take the time to test this and report back here.

**Comment by rgomez-eng** [comment]
Seems to be the same result. Here is what I added in the config file.

```
[global]
(...)
insecure-skip-verify = true
```
I believe the image used is correct.

```
root@docker1:~# docker image ls | grep chad
premoweb/chadburn                                                      latest     ae7be98d685a   3 hours ago     20.5MB
```

Maybe I did something wrong?

**Comment by rgomez-eng** [comment]
You have this now,

```
	d := gomail.NewPlainDialer(m.SMTPHost, m.SMTPPort, m.SMTPUser, m.SMTPPassword)
	if err := d.DialAndSend(msg); err != nil {
		return err
	}

	// InsecureSkipVerify is used to skip the certificate verification
	if m.InsecureSkipVerify == true {
		d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
	}
```
But I believe it should be like this,

```
	d := gomail.NewPlainDialer(m.SMTPHost, m.SMTPPort, m.SMTPUser, m.SMTPPassword)
	// InsecureSkipVerify is used to skip the certificate verification
	if m.InsecureSkipVerify == true {
		d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
	}
	
	if err := d.DialAndSend(msg); err != nil {
		return err
	}
```
Did a quick test and it seems to work.
