### ISSUE TITLE
Email reporting: allow SMTP auth on unencrypted connections

### ISSUE THREAD

**Issue by TheLastProject** [PremoWeb/chadburn#26]
Copied from https://github.com/mcuadros/ofelia/issues/173 as Ofelia seems unmaintained:

I want to use the email option together with [gotify-smtp](https://github.com/tystuyfzand/gotify-smtp), which requires you to put the destination user that should receive the notifications in the authentication username field. However, Ofelia refuses to allow this:
```
mail.go:57 ▶️ ERROR Mail error: "unencrypted connection"
```

In general, I totally agree with this behaviour. But given I am only trying to communicate to another Docker container on the same network, there is no security issue that I can tell from using an unencrypted connection. It would be nice if there could be an option to allow authenticating over an unencrypted connection (disabled by default, of course). Thank you for considering :)

**Comment by TheLastProject** [comment]
I see this situation should've been improved in #22, but even with `insecure-skip-verify` I am still getting this error on the latest Docker build (1.0.2.1), so it seems that `insecure-skip-verify` may allow bad certs but no lack of SSL altogether.

**Comment by maietta** [comment]
After reading up a bit on Gotify and Gotify-SMTP, it seems like this would be better suited as a middleware implementation rather than adapting the existing mail middleware to use it.

If I understand this right, Gotify-SMTP wouldn't even be needed. The middleware could login/push messegaes as described here: https://gotify.net/docs/pushmsg.

**Comment by TheLastProject** [comment]
Direct talking to Gotify would solve my issue better yeah

**Comment by maietta** [comment]
Okay, then.

I'll attempt to write a middleware component today. I first need to familiarize myself with using Gotify.

**Comment by maietta** [comment]
How silly of me!

Gotify is already available as a middleware component in Chadburn. HOWEVER, it's not documented.

See:
https://github.com/PremoWeb/chadburn/blob/main/middlewares/gotify.go

I guess today I'll switch gears and move back onto documentation.

The flag you will need is gotify-webhook

**Comment by TheLastProject** [comment]
Awesome, it works great! I'll close this then as I have no need for this feature given Gotify works, but I've made https://github.com/PremoWeb/chadburn/pull/27 to improve the documentation.

**Comment by maietta** [comment]
Thank you, @TheLastProject.
