### ISSUE TITLE
Config file cannot be loaded on startup

### ISSUE THREAD

**Issue by boindil** [PremoWeb/chadburn#28]
I'm not yet sure as to why this is happening, but my config file wont read at startup and thus I dont get logging right.

I am using the latest docker container and I've tried mounting the config file via volume, copying it into /tmp in the container and even setting chmod to 777.

I did also start chadburn a second time inside the container - with same results. Logging would be really great as I cannot get my jobs working. Surprisingly the config file gets loaded successfully for the jobs - even though they are not working.

```
/ # /usr/bin/chadburn daemon --config=/tmp/chadburn.conf 
daemon.go:41 ▶ DEBUG Config file: /tmp/chadburn.conf not found
scheduler.go:45 ▶ NOTICE New job registered "autoprint-test1" - "cd /app/autoprint/test1 && php -q index.php" - "@every 2m" - ID: 1
scheduler.go:45 ▶ NOTICE New job registered "autoprint-test2" - "cd /app/autoprint/test2 && php -q index.php" - "@every 2m" - ID: 2
scheduler.go:56 ▶ DEBUG Starting scheduler
cron_utils.go:13 ▶ DEBUG start
cron_utils.go:13 ▶ DEBUG schedule
cron_utils.go:13 ▶ DEBUG schedule
scheduler.go:50 ▶ NOTICE Job deregistered (will not fire again) "autoprint-test1" - "cd /app/autoprint/test1 && php -q index.php" - "@every 2m" - ID: 1
scheduler.go:50 ▶ NOTICE Job deregistered (will not fire again) "autoprint-test2" - "cd /app/autoprint/test2 && php -q index.php" - "@every 2m" - ID: 2
cron_utils.go:13 ▶ DEBUG removed
cron_utils.go:13 ▶ DEBUG removed
```

```
/ # cat /tmp/chadburn.conf 
[global]
save-folder = /etc/logs

[job-exec "autoprint-test1"]
schedule = @every 2m
container = autoprint
network = mybridge
command = cd /app/autoprint/test1 && php -q index.php

[job-exec "autoprint-test2"]
schedule = @every 2m
container = autoprint
network = mybridge
command = cd /app/autoprint/test2 && php -q index.php
```

```
/ # ping autoprint
PING autoprint (172.19.0.4): 56 data bytes
64 bytes from 172.19.0.4: seq=0 ttl=64 time=0.112 ms
64 bytes from 172.19.0.4: seq=1 ttl=64 time=0.075 ms
^C
--- autoprint ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.093/0.112 ms
```

**Comment by maietta** [comment]
Have you mounted the config from host to container when running?

```
docker run -it --rm \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v  /path/on/host/chadburn.conf:/tmp/chadburn.conf:ro \
        premoweb/chadburn:latest daemon
```

**Comment by boindil** [comment]
Hi @maietta 
I am using portainer for that, so it's more like the first variant even though I did not start via command line. I did already try to provide the file via bind-mound and inside a volume.

When entering the container I see the file is definitely mounted and still I am getting that log. I would understand if there was "something missing" on container start and that was my first thought, too. Thats why I started chadburn manually inside the docker container "a second time" after the container came up.

Maybe you have some more ideas, but otherwise I'm probably going to compile chadburn myself the next days trying to figure stuff out. Just from looking at the code I could not identify anything yet leaving me with no clue on whats happening here ...

**Comment by maietta** [comment]
Interesting.

I am right in the middle of a paid project so I can feed myself more coffee, so but I'll be working to test this early on when I get back to work on this in the next few days. Please let me know what you discover if you do discover something broken.

I forked this project and patched in a few changes, but I wasn't the one who wrote the software, so I am not fully versed just how exactly it works. I'm doing a major overhaul on for 2.x which will address a huge list of problems that were never fixed or only partially fixed. I am starting a website at https://chadburn.app in order to document various use-case scenarios with examples, how to build and test, etc. I also want to provide visual diagrams using MermaidJS so it's easy to see how to fix or expand it's capabilities.

None of this helps you right now, though. (sorry)

**Comment by boindil** [comment]
I think I've narroved my problems down to different things:

Loading the config file will fail if job-exec contains the "network"-key. Once i add that, the file will not load on startup.

For some reason https://github.com/PremoWeb/chadburn/blob/939d851e67b20c32eaa5b6363e29cc719615df1d/cli/config.go#L147 will always remove my exec job. I've tried "chadburn.enable = true" as label on the target container, but that does nothing as it will just continue here https://github.com/PremoWeb/chadburn/blob/939d851e67b20c32eaa5b6363e29cc719615df1d/cli/docker-labels.go#L42 and not add the job to the list here https://github.com/PremoWeb/chadburn/blob/939d851e67b20c32eaa5b6363e29cc719615df1d/cli/docker-labels.go#L56

That being said there currently seems no way for me to add the exec-job by providing the ini-file only as it will always delete my job if it's not being found in the label-determined exec-jobs.

Since I do not know much about the library itself and the reasoning for this code I don't think I should help out with a PR here. So can you help out here? Otherwise I could guess and do it anyways, but I don't know if the tests provided in this project are sufficient.

**Comment by maietta** [comment]
Thank you very much, @boindil.

I've been quite busy on paid projects so I'll try and get to this in the next couple of days. I'll be working through the 4th of July holiday (tomorrow).

I appreciate that you dug through the code and doing your best in troubleshooting.

No promises, but I'll do my best!

Happy 4th!

**Comment by boindil** [comment]
@maietta could you please have a look? Currently the configuration via config file is not working because jobs are always dropped when synced with docker labels. This is because the check only re-reads the docker labels.

In #45 I worked around this successfully by adding a few lines to "tag the source" - thus having the meta-information whether the job is controlled by docker-labels or the config-file.

As an alternative it would be possible to re-read the config-file together with the docker-labels.

Another thing that comes to mind: whats with having the same job-name both in configuration file and docker labels.
