### ISSUE TITLE
Add ability to disable docker dependencies.

### ISSUE THREAD

**Issue by martadinata666** [PremoWeb/chadburn#5]
As `chadburn` intended to use together with another container via `labels`.  It possible to run standalone, I intended to include the binary, and run `JOB-LOCAL` only, but it need to mount `/var/run/docker.sock`. The job itself doesn't related to docker, can we get option to disable docker sock dependency? Like use `--disable-docker` so chadburn will only execute `JOB-LOCAL` even there is another type jobs.

Anyway great works, at least some cron with real funtion with docker.

**Comment by maietta** [comment]
By design, it's designed to work in Docker environments. It is written to listen to Docker daemon events and any changes in the service labels of running containers. To disable access to the socket would disable it's ability to operate at all.

**Comment by maietta** [comment]
Okay, I see it's use-case potential. This will get implemented in version 2.x, onwards. This project is slow due to being and unpaid project, so I apologize for the slowness!
