### ISSUE TITLE
Known memory leak issue possible.

### ISSUE THREAD

**Issue by maietta** [PremoWeb/chadburn#7]
As maintainer of this Chadburn fork of Ofelia, I am concerned about the problem of memory leaks for at least some users.

mcuadros/ofelia#107

Thank you @helmut72 for raising this issue over at the Ofelia project. I'm tracking it here as well.

A feature request to switch to Chadburn has been raised but another question was raised about the known memory leak issue. See:  
mailcow/mailcow-dockerized#4362

I am creating this issue for others who may have come across this problem in Chadburn. Since this was raised with Ofelia project, the focus should remain there, however this issue will get updated when I or others discover relevant updates addressing the problem.

**Comment by maietta** [comment]
As I am reading through, I notice this issue was previously closed as there was a pull request addressing the problem

See: mailcow/mailcow-dockerized#4362

Obviously, others are having issues. It is unclear to me if the problem people are having the same or different root cause. Since I am new to Mailcow myself, I setting up a throw-away VPS for testing. Updates forthcoming.

**Comment by helmut72** [comment]
Hello Nick, I have 4 Ofelia instances running for many months and they don't show any problems for me. Looks like the memory leak is fixed at least for me. But I think I should give Chadburn a try, if development continues.

**Comment by maietta** [comment]
Hi @helmut72.

I forked the Mailcow project and swapped out Ofelia with the latest version of Chadburn to see how that would work. I setup one of my test domains (bugkillerz.com) on a 8GB ram VPS running Ubuntu 20.10 and so far, ram has not spiked above 3GB. I will leave this running for a while.

The only scenario I have seen where people are experiencing issues seems to be when jobs mail fail to be seen as completed. One way to address this may be to enable the no-overlap rule in Ofelia or Chadburn. I'm almost certain we are good to go with Mailcow if the no-overlap rule is added, giving previous jobs a chance to complete on their own.

chadburn.job-exec.process\_tables.no-overlap: "true"

**Comment by maietta** [comment]
The first memory leak issue was reproducible but has been addressed a previous commit to Ofelia prior to the hard fork called Chadburn.

This particular issue is not reproducible in my testing. Please re-open if further data is available.
