### ISSUE TITLE
Is Chadburn discontinued?

### ISSUE THREAD

**Issue by scls19fr** [PremoWeb/chadburn#73]
Hello,

I noticed on

https://www.libhunt.com/r/chadburn

that Chadburn is considered as "DISCONTINUED"

What is your opinion?

Kind regards

**Comment by maietta** [comment]
That's a lie. They could have reached out to me first, but they did not.

**Comment by scls19fr** [comment]
Thanks for prompt answer. So closing. But I think you should probably ask them.

**Comment by maietta** [comment]
Thank you for alerting me to this.

I'm having legal look at this.
